// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSsE8Ax8D9IghuOpKhYPJtwcRzD8pxQE',
    appId: '1:616941545128:web:c17239d5057f88c9af449d',
    messagingSenderId: '616941545128',
    projectId: 'intelliviaje',
    authDomain: 'intelliviaje.firebaseapp.com',
    storageBucket: 'intelliviaje.firebasestorage.app',
    measurementId: 'G-DHE7528V4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkpghXH-XJPYI9B4i7TuiL1azN_qVkcOY',
    appId: '1:616941545128:android:49e76878dd390795af449d',
    messagingSenderId: '616941545128',
    projectId: 'intelliviaje',
    storageBucket: 'intelliviaje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePuRwPJhTYDQWH44q90wC6PFoBM69DhA',
    appId: '1:616941545128:ios:97f2ab10141d0a4baf449d',
    messagingSenderId: '616941545128',
    projectId: 'intelliviaje',
    storageBucket: 'intelliviaje.firebasestorage.app',
    iosBundleId: 'com.example.flutterIntelli2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBePuRwPJhTYDQWH44q90wC6PFoBM69DhA',
    appId: '1:616941545128:ios:97f2ab10141d0a4baf449d',
    messagingSenderId: '616941545128',
    projectId: 'intelliviaje',
    storageBucket: 'intelliviaje.firebasestorage.app',
    iosBundleId: 'com.example.flutterIntelli2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJSsE8Ax8D9IghuOpKhYPJtwcRzD8pxQE',
    appId: '1:616941545128:web:730e0c3c1c3baf63af449d',
    messagingSenderId: '616941545128',
    projectId: 'intelliviaje',
    authDomain: 'intelliviaje.firebaseapp.com',
    storageBucket: 'intelliviaje.firebasestorage.app',
    measurementId: 'G-0ZGHGVQ3YL',
  );
}
